### PR TITLE
Exclude port count from link to category

### PR DESCRIPTION
**Pull request by mojca**
Thanks for the main change.
This is just a minor improvement which I feel this might look nicer.

### CODE REVIEW

**Comment by arjunsalyan** [comment]
I did try this and found the black and blue to be too contrasting. But that is just what I felt.
Maybe we need more improvements- like the count can be made greyish, instead of black. I will do these changes once we finalise.

Screenshot 2019-08-16 at 2 58 57 pm

**Comment by arjunsalyan** [comment]
This is how it looks after making the counts a bit grey.

Screenshot 2019-08-16 at 3 02 07 pm

**Comment by mojca** [comment]
Gray looks better.

**Comment by neverpanic** [comment]
That may be harder to do, but can we right-align the grey port count and get rid of the brackets?

**Comment by arjunsalyan** [comment]
> That may be harder to do, but can we right-align the grey port count and get rid of the brackets?

Screenshot 2019-08-16 at 8 43 36 pm

I can't really decide now. This seems to be better, maybe.

**Comment by mojca** [comment]
All look fine, the latest screenshot is probably best. (Feel free to merge any of them.)

**Comment by umeshksingla** [comment]
If it’s about vote now, I’ll go with the latest screenshot too.

**Comment by arjunsalyan** [comment]
Changes are now live at: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com

And the live closed maintainer icon can be seen here: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com/port/CronniX/?tab=summary

**Comment by mojca** [comment]
Thanks. On mobile phone it looks strange as some numbers go to 2nd row.

**Comment by arjunsalyan** [comment]
> Thanks. On mobile phone it looks strange as some numbers go to 2nd row.

Yes, we have lesser space on mobile phone. I think we should simply hide the count on smaller screens?

**Comment by mojca** [comment]
Or decrease column count.

**Pull request merged**
