### PR TITLE
Fix x-axis sorting in port versions chart

### LINKED ISSUE #112: Strange x axis sorting for installed port versions chart
Sorting of the port versions in the chart showing the installed versions appears to be done in decreasing order of frequency, so the version with the most stats on the left, least on the right. In my opinion this is a strange inconvenient scheme. It would be better to sort accordingly to the version itself, so oldest in the left, newest in the right.

See attached screen shot taken from

https://ports.macports.org/port/clang-8.0/stats?days=30&days_ago=0

PNG image

My suggestion would flip 8.0.0_0 with 8.0.0_1

### PR DESCRIPTION
**Pull request by arjunsalyan**
Closes: https://github.com/macports/macports-webapp/issues/112

### CODE REVIEW

**Comment by arjunsalyan** [comment]
This is a minor change, so I believe it can be merged right away.

**Comment by mojca** [comment]
I'm on my phone at the moment. If you tested it, feel free to simply merge it.

**Comment by cjones051073** [comment]
Just for my info, When will this fix hit the main server ? The issue is still present at

https://ports.macports.org/port/clang-8.0/stats?days=30&days_ago=0

**Comment by arjunsalyan** [comment]
It has been deployed. The versions are sorted correctly for me. Highest version (8.0.1_0) on left and decreasing as we go right.

**Comment by cjones051073** [comment]
> It has been deployed. The versions are sorted correctly for me. Highest version (8.0.1_0) on left and decreasing as we go right.

Thats the wrong way around, for me. Graphs have the lowest (oldest) on the left and highest(newest) on the right. What you have is backwards to that standard convention. 

Actually, now I look again I would argue all your graphs have the x axis sorting backwards...

**Comment by mojca** [comment]
I think we started discussing at some time whether to sort the OS versions chronologically from left to right, or whether to start with the one that's most important on the left, and then you can mostly ignore the rest of the x axis.

As far as "User vs Version for each month" (which could get a better name) goes, I would leave the sorting on the y axis precisely as it is (the latest version on top). Same for xcode versions etc.

For port version & macports version I would tend to agree that increasing version from left to the right kind of makes more sense.

I'm pretty much indifferent about the sorting order on the x axis for macOS versions, but if we want to keep it consistent with the rest, it might as well be swapped around. But we'll probably need to remove `OS:` prefix which is by now taking way too much space.

I don't have super strong feelings though.

**Pull request merged**
