### PR TITLE
Delay search by 1000ms after user stops typing and other improvements

### PR DESCRIPTION
**Pull request by arjunsalyan**
- [x] Trigger search only after user stops typing (with a delay of 1000ms)
- [x] Use loader image for searching
- [x] Improve JS code for maintainers, category and variants pages

Deployed on EC2: http://ec2-52-34-234-111.us-west-2.compute.amazonaws.com

### CODE REVIEW

**Comment by umeshksingla** [comment]
This looks nice. The only caveat I feel is if I remove the last characters using `delete` button, it doesn't fire search again.

**Comment by mojca** [comment]
On my mobile phone the search no longer works at all. I tried two browsers (Chrome, Samsung's own)

**Comment by arjunsalyan** [comment]
Both of these issues:
1. Backspace not working
2. Search not working on mobile unless you push enter

are caused by the use of `keypress`. I will fix this.

**Comment by arjunsalyan** [comment]
Both of the issues are now solved. On mobile it will work once you clear previous website data.

**Review by umeshksingla — APPROVED** [review]

**Comment by mojca** [comment]
Works for me as well.

**Comment by mojca** [comment]
Feel free to merge. My javascript is pretty weak, so I cannot do a good CR anyway.

**Comment by umeshksingla** [comment]
@arjunsalyan @mojca 
how do you wish to work on the autofocus of the search bar feature, raised by Clemens in #105? This PR, a new PR or should I add it to the feature requests google doc?

**Comment by arjunsalyan** [comment]
> @arjunsalyan @mojca
> how do you wish to work on the autofocus of the search bar feature, raised by Clemens in #105? This PR, a new PR or should I add it to the feature requests google doc?

I will create a new PR very soon for this. But we want this functionality on just the homepage, right? Or do we want it everywhere where we have the search-bar.

**Pull request merged**
