### PR TITLE
Alter time_elapsed field in BuildHistory Model

### LINKED ISSUE #124: Cron fails with djano.core.exceptions.ValidationError
```
Cronic detected failure or error output for the command:
/var/www/webapp/cron.sh

RESULT CODE: 1

ERROR OUTPUT:
Traceback (most recent call last):
  File "/code/app/manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/dist-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/code/app/ports/management/commands/fetch-build-history.py", line 11, in handle
    BuildHistory.populate()
  File "/code/app/ports/models/buildhistory.py", line 114, in populate
    load_database(build_data_summary)
  File "/code/app/ports/models/buildhistory.py", line 95, in load_database
    build.save()
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1334, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1278, in as_sql
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1278, in <listcomp>
    for obj in self.query.objs
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1277, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/sql/compiler.py", line 1218, in prepare_value
    value = field.get_db_prep_save(value, connection=self.connection)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 789, in get_db_prep_save
    return self.get_db_prep_value(value, connection=connection, prepared=False)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2218, in get_db_prep_value
    value = self.get_prep_value(value)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2213, in get_prep_value
    return self.to_python(value)
  File "/usr/local/lib/python3.6/dist-packages/django/db/models/fields/__init__.py", line 2200, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'1 day, 7:23:56' value has an invalid format. It must be in HH:MM[:ss[.uuuuuu]] format."]

STANDARD OUTPUT:
```

### PR DESCRIPTION
**Pull request by arjunsalyan**
Closes: https://github.com/macports/macports-webapp/issues/124

### CODE REVIEW

**Comment by umeshksingla** [comment]
If we are not doing any calculations over it and the format is not understood by the app/python directly, I'd say we should keep it simply as a string?

**Comment by arjunsalyan** [comment]
> If we are not doing any calculations over it and the format is not understood by the app/python directly, I'd say we should keep it simply as a string?

It stores a `timedelta` object which does not support custom formatting. So `DurationField` seems just the right choice for it.

**Comment by umeshksingla** [comment]
It does. I wasn't aware of the format returned by the buildbot.

**Review by umeshksingla — APPROVED** [review]

**Comment by mojca** [comment]
Is the migration really so simple and the conversion works out of the box? Will the app redo fetching data from the failed parsing cases?

Looks ok to me in any case, duration makes more sense than useless string.

**Comment by arjunsalyan** [comment]
> Is the migration really so simple and the conversion works out of the box?

Yes. We were already storing a `timedelta` object in this field, which is supported by `DurationField`.

> Will the app redo fetching data from the failed parsing cases?

Yes, the app always starts fetching from `last build id + 1` build for each builder.

I have also tested this on EC2.

**Comment by arjunsalyan** [comment]
If this looks good, we should merge it asap. We are missing on updates due to this.

**Pull request merged**
